### ISSUE TITLE
spelling/ verb form mistake

### ISSUE THREAD

**Issue by FanielS** [MG-Musty/load-balancer-with-nginx_web_server#1]
This tutorial will   <U>*__teacher__*  <U>  you how to install configure your Load_balancer using HAproxy on Ubuntu 20.04 running on a Nginx web_server.

**Comment by MG-Musty** [comment]
> This tutorial will _**teacher**_ you how to install configure your Load_balancer using HAproxy on Ubuntu 20.04 running on a Nginx web_server.

Thank you for pointing out the misspell, sometimes things of such happens 🤗

**Comment by MG-Musty** [comment]
Have corrected the mistake.
